68–95–99.7 rule
====
https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule



- In statistics, the 【68–95–99.7】 rule, 
- also known as the empirical rule, 
- is a shorthand used to remember the percentage of values 
- that lie within a band around the mean in a normal distribution 
- with a width of two, four and six standard deviations, respectively; 
- more accurately, 
- 68.27%, 95.45% and 99.73% of the values 
- lie within 1, 2 and 3 standard deviations of the mean, respectively.
- 
    * 在統計中，68–95–99.7規則（也稱為經驗規則）是一種簡寫形式，
    * 用於記住寬度為2、4和6的正態分佈中均值周圍的帶內值的百分比 偏差； 
    * 更準確地說，這些值的68.27％，95.45％和99.73％
    * 分別位於平均值的 1 ， 2 和 3 個標準差之內。

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/7d77a583313359c3719a78401a7c3cb1ea3ce405)

![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Empirical_rule_histogram.svg/450px-Empirical_rule_histogram.svg.png)




In [1]:
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as pl
import pandas as pd


In [2]:
st.norm.cdf(x=[-3,-2,-1,0])

array([0.0013499 , 0.02275013, 0.15865525, 0.5       ])

In [23]:
st.norm.ppf(q=[.001, .005, .01, .025, .05])


array([-3.09023231, -2.5758293 , -2.32634787, -1.95996398, -1.64485363])

In [25]:
# Prob("X <= x" |(given that) X is normal, mu=0, sigma=1)
cdf= st.norm.cdf(x=[-3.10, -2.58, -2.33, -1.96, -1.65])
np.round(cdf, decimals=3)


array([0.001, 0.005, 0.01 , 0.025, 0.049])

$ x_.025 = 1.96, $

$
P("-x_.025\le X \le x_.025") 
= 
1 -  P("X \le -x_.025") - P("X \ge +x_.025") 
= 1 - .025 - .025
= 0.95
$

$ x_.005 = 2.58, $

$
P("-x_.005\le X \le x_.005") 
= 0.99
$

$$
P("-x_0\le X \le x_0") 
= 1 - ( P("X \le -x_0") 
      + P("X \ge +x_0") ) 
= 0.95
$$

$$
E= 
\frac
 {m \space c^2}
 {\sqrt
   {1-\frac
       {v^2}
       {c^2}
   }
 }
$$

$$
\left(
 \left(  
   \frac{ N } 
        { \left(
            \frac{L}
                 {p} 
          \right)  
          - (m+n)}  
 \right)
\right)
$$

You can use 
$$\LaTeX$$ 
to typeset formulas. 

A formula can be displayed inline, 
e.g. 
$$ e=mc^2 $$, 

or as a block:

$$
\int_\Omega \nabla u \cdot \nabla v~dx = \int_\Omega fv~dx
$$



Greek alphabet
====

https://en.wikipedia.org/wiki/Greek_alphabet

Α, α,	Alpha	
Β, β,	Beta	
Γ, γ,	Gamma	
Δ, δ,	Delta	
Ε, ε,	Epsilon	
Ζ, ζ,	Zeta	
Η, η,	Eta	Ττ	
Θ, θ,	Theta	
Ι, ι,	Iota	
Κ, κ,	Kappa	
Λ, λ,	Lambda	
Μ, μ,	Mu	
.............. 
Ν, ν,	Nu
Ξ, ξ,	Xi
Ο, ο,	Omicron
Π, π,	Pi
Ρ, ρ,	Rho
Σ, σ,ς,	Sigma
Τ, τ,   Tau,
Υ, υ,	Upsilon
Φ, φ,	Phi
Χ, χ,	Chi
Ψ, ψ,	Psi
Ω, ω,   Omega

 Α α, Β β, Γ γ, Δ δ, 
 Ε ε, Ζ ζ, 
 Η η, Θ θ, 
 Ι ι, Κ κ, Λ λ, Μ μ, Ν ν, Ξ ξ, 
 Ο ο, Π π, Ρ ρ, Σ σ/ς, Τ τ, 
 Υ υ, Φ φ, Χ χ, Ψ ψ, Ω ω.
 


Greek letter in Markdown
====

$A$ $B$ $\Gamma$ $\Delta$

$E$ $Z$

$H$ $\Theta$

$I$ $K$ $\Lambda$ $M$ $N$ $\Xi$

$O$ $\Pi$ $P$ $\Sigma$ $T$

$Y$ $\Phi$ $X$ $\Psi$

$\Omega$



𝐴 𝐵 Γ Δ
𝐸 𝑍
𝐻 Θ
𝐼 𝐾 Λ 𝑀 𝑁 Ξ
𝑂 Π 𝑃 Σ 𝑇
𝑌 Φ 𝑋 Ψ
Ω

ΑΒΓΔ
ΕΖ
ΗΘ
ΙΚΛMNΞ
OΠΡΣΤ
ΥΦΧΨ
Ω

In [ ]:
# Greek Letter in Code (Jupiter, Python)
ΑΒΓΔ
ΕΖ
ΗΘ
ΙΚΛMNΞ
OΠΡΣΤ
ΥΦΧΨ
Ω

In [2]:
st.norm.isf(.025)

1.9599639845400545

In [5]:
st.binom.ppf(q=.025,n=100,p=.2), st.binom.isf(q=.025,n=100,p=.2)

(12.0, 28.0)

In [6]:
st.binom.ppf(q=.025,n=100,p=.8), st.binom.isf(q=.025,n=100,p=.8)

(72.0, 88.0)